#! /bin/sh
#|
exec racket -tm "$0" -- ${1+"$@"}
|#
#lang racket/base

(require "Other/xyes.rkt")

(provide main)

(define (main . a)
  ;; Print every element in the stream
  (for ([i (xyes a)]) (displayln i)))
  