#! /bin/sh
#|
exec racket -tm "$0" -- ${1+"$@"}
|#
#lang racket/base

(require racket/cmdline
         "Other/xtcp.rkt")

(module+ main
  (command-line
   #:program "xtcp"
   #:args ([port (number->string DEFAULT-PORT)])
   (xtcp (string->number port))))
